version: '3.3'

services:

 react:
  build: ./react-app
  ports:
   - 127.0.0.1:4000:3000
   # - 127.0.0.1:8080:8080
  volumes:
   - ./react-app/src:/app/src

 mongodb:
  image: mongo
  # ports:
  #  - 127.0.0.1:27017:27017
  volumes:
    - ./mongodb/data/db/:/data/db/
  # environment:
    # - MONGO_INITDB_DATABASE=i2b2Ontologies
    # - MONGO_INITDB_ROOT_USERNAME=admin
    # - MONGO_INITDB_ROOT_PASSWORD=password

 node:
  build: ./nodeApp
  ports:
   - 127.0.0.1:3000:3000
   # - 127.0.0.1:8080:8080
  volumes:
   - ./nodeApp/app:/app/

 mongo-express:
   image: mongo-express
   ports:
     - 127.0.0.1:8081:8081
   environment:
    - ME_CONFIG_MONGODB_SERVER=mongodb
    # - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
    # - ME_CONFIG_MONGODB_ADMINPASSWORD=password
    # - ME_CONFIG_MONGODB_PORT=27017
    # - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
    - ME_CONFIG_BASICAUTH_USERNAME=test
    - ME_CONFIG_BASICAUTH_PASSWORD=test
