const PARSE_PROJECTS = 'nav/PARSE_PROJECTS';
const FETCH_PROJECTS = 'nav/FETCH_PROJECTS';
const FETCH_PROJECTS_SUCCESS = 'nav/FETCH_PROJECTS_SUCCESS';
const FETCH_PROJECTS_ERROR = 'nav/FETCH_PROJECTS_ERROR';

const CREATE_PROJECTS = 'nav/CREATE_PROJECTS';
const CREATE_PROJECTS_SUCCESS = 'nav/CREATE_PROJECTS_SUCCESS';
const CREATE_PROJECTS_ERROR = 'nav/CREATE_PROJECTS_ERROR';

const SHOW_CREATE_PROJECT_MODAL = 'nav/SHOW_CREATE_PROJECT_MODAL';
const HIDE_CREATE_PROJECT_MODAL = 'nav/HIDE_CREATE_PROJECT_MODAL';

const SHOW_PROJECT_VERSIONS_MODAL = 'nav/SHOW_PROJECT_VERSIONS_MODAL';
const HIDE_PROJECT_VERSIONS_MODAL = 'nav/HIDE_PROJECT_VERSIONS_MODAL';


const SET_FILE_ID = 'project/SET_FILE_ID';


export default {
  FETCH_PROJECTS,
  FETCH_PROJECTS_SUCCESS,
  FETCH_PROJECTS_ERROR,
  PARSE_PROJECTS,
  SHOW_CREATE_PROJECT_MODAL,
  HIDE_CREATE_PROJECT_MODAL,
  CREATE_PROJECTS,
  CREATE_PROJECTS_SUCCESS,
  CREATE_PROJECTS_ERROR,
  SET_FILE_ID,
  SHOW_PROJECT_VERSIONS_MODAL,
  HIDE_PROJECT_VERSIONS_MODAL

}
