const DELETE_PROJECT_START = "project/DELETE"
const DELETE_PROJECT_SUCCESS = "project/DELETE_PROJECT_SUCCESS"
const DELETE_PROJECT_ERROR = "project/DELETE_PROJECT_ERROR"

export default {
  DELETE_PROJECT_START,
  DELETE_PROJECT_SUCCESS,
  DELETE_PROJECT_ERROR

}
